server:
  port: 8001
  servlet-path: /*

security:
  oauth2:
    client:
      clientId: employee-service
      clientSecret: 4bb023e3-1a0f-4048-8b4f-6cf0abc59cd4
    resource:
      tokenInfoUri: http://localhost:8083/auth/realms/dev/protocol/openid-connect/token/introspect